spring:
  application:
    name: item-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin
    
server:
  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://176.13.20.132:2001/, http://176.13.20.132:2002/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
